export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_REQUEST_SUCCESS = 'SIGN_IN_REQUEST_SUCCESS';
export const SIGN_IN_REQUEST_FAIL = 'SIGN_IN_REQUEST_FAIL';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_REQUEST_SUCCESS = 'SIGN_OUT_REQUEST_SUCCESS';