export const FIND_ALL_PARCEL_REQUEST = 'FIND_ALL_PARCEL_REQUEST';
export const FIND_ALL_PARCEL_REQUEST_SUCCESS = 'FIND_ALL_PARCEL_REQUEST_SUCCESS';
export const FIND_ALL_PARCEL_REQUEST_FAIL = 'FIND_ALL_PARCEL_REQUEST_FAIL';

export const FIND_ALL_BIKER_PARCEL_REQUEST = 'FIND_ALL_BIKER_PARCEL_REQUEST';
export const FIND_ALL_BIKER_PARCEL_REQUEST_SUCCESS = 'FIND_ALL_BIKER_PARCEL_REQUEST_SUCCESS';
export const FIND_ALL_BIKER_PARCEL_REQUEST_FAIL = 'FIND_ALL_BIKER_PARCEL_REQUEST_FAIL';

export const HIDE_SIDE_CONTAINER = 'HIDE_SIDE_CONTAINER';
export const SHOW_CREATE_FORM = 'SHOW_CREATE_FORM';
export const SHOW_EDIT_FORM = 'SHOW_EDIT_FORM';

export const CREATE_PARCEL_REQUEST = 'CREATE_PARCEL_REQUEST';
export const CREATE_PARCEL_REQUEST_SUCCESS = 'CREATE_PARCEL_REQUEST_SUCCESS';
export const CREATE_PARCEL_REQUEST_FAIL = 'CREATE_PARCEL_REQUEST_FAIL';

export const UPDATE_PARCEL_REQUEST = 'UPDATE_PARCEL_REQUEST';
export const UPDATE_PARCEL_REQUEST_SUCCESS = 'UPDATE_PARCEL_REQUEST_SUCCESS';
export const UPDATE_PARCEL_REQUEST_FAIL = 'UPDATE_PARCEL_REQUEST_FAIL';